#!/usr/bin/perl
use 5.016;
use warnings;
use utf8;

# conjuguer - french verb conjugation website
# https://raf.org/conjuguer
# https://github.com/raforg/conjuguer
# https://codeberg.org/raforg/conjuguer
#
# Copyright (C) 2003-2007, 2023 raf <raf@raf.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#
# 20230408 raf <raf@raf.org>

# audit - Check that the output of conjuguer with no argumens looks OK
# Used by make output
# usage: ./conjuguer > output; ./audit output

use open qw(:std :encoding(UTF-8));

my $w = "a-zàáâäèéêëìíîïòóôöùúûüç()/'-";
my $e = "uéiïstû";

while (<>)
{
	next if /^$/;

	if (/Indicatif Présent/ || /Indicatif Imparfait/ || /Indicatif Passé simple/ || /Indicatif Futur simple/ || /Conditionnel Présent/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			print 'SIMP: ', $line unless /^[$w]+$/;
		}
	}
	elsif (/Indicatif Passé composé/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(ai |as |a |avons |avez |ont |suis |es |est |sommes |êtes |sont )//;
			print 'IPC: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Indicatif Plus-que-parfait/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(avais |avais |avait |avions |aviez |avaient |étais |étais |était |étions |étiez |étaient )//;
			print 'IPQP: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Indicatif Passé antérieur/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(eus |eus |eut |eûmes |eûtes |eurent |fus |fus |fut |fûmes |fûtes |furent )//;
			print 'IPA: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Indicatif Futur antérieur/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(aurai |auras |aura |aurons |aurez |auront |serai |seras |sera |serons |serez |seront )//;
			print 'IFA: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Indicatif Futur proche/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(vais |vas |va |allons |allez |vont )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			print 'IFP: ', $line unless /^[$w]+(er|ir|ïr|re)$/;
		}
	}
	elsif (/Indicatif Passé récent/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(viens |vient |venons |venez |viennent | )//;
			s/^(d'|de )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			print 'IPP: ', $line unless /^[$w]+(er|ir|ïr|re)$/;
		}
	}
	elsif (/Indicatif Passé surcomposé/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(ai eu |as eu |a eu |avons eu |avez eu |ont eu |ai été |as été |a été |avons été |avez été |ont été )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			print 'IPSC: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Subjonctif Présent/ || /Subjonctif Imparfait/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:qu'|que )//;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			print 'S: ', $line unless /^[$w]+$/;
		}
	}
	elsif (/Subjonctif Passé/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:qu'|que )//;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(?:aie |aies |ait |ayons |ayez |aient |sois |soit |soyons |soyez |soient )//;
			print 'SP: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Subjonctif Plus-que-parfait/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:qu'|que )//;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(?:eusse |eusses |eût |eussions |eussiez |eussent |fusse |fusses |fût |fussions |fussiez |fussent )//;
			print 'SPQP: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Impératif Présent/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/-t'en$/-toi en/;
			s/-(toi|nous|vous)([ -]en)?$//;
			print 'IMP.PRES: ', $line unless /^[$w]+$/;
		}
	}
	elsif (/Impératif Passé/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(aie |ayons |ayez |sois |soyons |soyez )//;
			s/^(en )//;
			print 'IMP.PASS: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Conditionnel Passé première forme/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(aurais |aurait |aurions |auriez |auraient |serais |serait |serions |seriez |seraient )//;
			print 'CP1: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Conditionnel Passé deuxième forme/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:j'|je |tu |il |nous |vous |ils )//;
			s/^(?:m'|me |t'|te |s'|se |nous |vous |se )//;
			s/^(en )//;
			s/^(eusse |eusses |eût |eussions |eussiez |eussent |fusse |fusses |fût |fussions |fussiez |fussent )//;
			print 'CP2: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (/Participe Présent/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:s'|se )//;
			s/^en //;
			print 'PARTPRES: ', $line unless /^[$w]+ant$/;
		}
	}
	elsif (/Participe Passé/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/\b(?:s'|se )//g;
			s/\ben //g;
			s/^(?:étant |ayant )//;
			s/,//;
			print 'PARTPASS: ', $line unless /^[$w]+[$e](?: [$w]+[$e]e)?$/;
		}
	}
	elsif (/Infinitif Présent/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:s'|se )//;
			s/^en //;
			print 'INFPRES: ', $line unless /^[$w]+(er|ir|ïr|re)$/;
		}
	}
	elsif (/Infinitif Passé/)
	{
		while (<>)
		{
			last if /^$/;
			next if /^N'existe pas/;
			my $line = $_;
			s/^(?:s'|se )//;
			s/^en //;
			s/^(?:être |avoir )//;
			print 'INFPASS: ', $line unless /^[$w]+[$e]s?$/;
		}
	}
	elsif (!/^Verbe / && !/^Conjugaison / && !/^     /)
	{
		print "ERROR: $_";
	}
}

# vim:set fenc=utf8:
# vi:set ts=4 sw=4:
